
# Pull base image.
FROM dockerfile/java

MAINTAINER Sam Lewis

# Add app
RUN mkdir /root/app
ADD app/app.jar /root/app/
ADD app/lib /root/app/lib

# Expose
EXPOSE 8080

# Run
CMD (cd /root/app; java -jar app.jar)
